### ISSUE TITLE
Directory in main git folder

### ISSUE THREAD

**Issue by JuniorJPDJ** [rafael59r2/waterfall-image#2]
Could you please move the project to main git folder?
This folder makes it impossible to automatically build your container from docker-compose using something like this:

```
services:
  waterfall:
    build: https://github.com/rafael59r2/waterfall-image.git
```

**Comment by rafael59r2** [comment]
Ok

**Comment by JuniorJPDJ** [comment]
Resolved in https://github.com/rafael59r2/waterfall-image/commit/24fa08c7476d252f1022fb2835078c988ce2ac66
